CREATE TABLE `amir_cs275`.`amir_project` (
  `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(64) UNIQUE,
  `zipcode` CHAR(5)      NOT NULL DEFAULT 10000,
  `ts`      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;
